// SRD 5.1 spell reference data (CC-BY-4.0), sourced from the open
// 5e-bits/5e-database project: https://github.com/5e-bits/5e-database
// Trimmed to mechanically relevant fields only (no spell description text).
import type { Dnd5eAbility } from "./dnd5e.js";

export interface SrdSpell {
  id: string;
  name: string;
  level: number;
  school: string;
  castingTime: string;
  range: string;
  duration: string;
  requiresAttackRoll?: boolean;
  saveAbility?: Dnd5eAbility;
  damageDice?: string;
  damageType?: string;
  ritual?: boolean;
  /** SRD class ids (lowercase) that can cast this spell, e.g. ["wizard", "sorcerer"]. */
  classes: string[];
}

export const SRD_SPELLS: SrdSpell[] = [
  { id: "acid-arrow", name: "Acid Arrow", level: 2, school: "Evocation", castingTime: "1 action", range: "90 feet", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "4d4", damageType: "Acid", classes: ["wizard"] },
  { id: "acid-splash", name: "Acid Splash", level: 0, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "1d6", damageType: "Acid", classes: ["sorcerer", "wizard"] },
  { id: "aid", name: "Aid", level: 2, school: "Abjuration", castingTime: "1 action", range: "30 feet", duration: "8 hours", classes: ["cleric", "paladin"] },
  { id: "alarm", name: "Alarm", level: 1, school: "Abjuration", castingTime: "1 minute", range: "30 feet", duration: "8 hours", ritual: true, classes: ["ranger", "wizard"] },
  { id: "alter-self", name: "Alter Self", level: 2, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["sorcerer", "wizard"] },
  { id: "animal-friendship", name: "Animal Friendship", level: 1, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "24 hours", saveAbility: "wis", classes: ["bard", "druid", "ranger"] },
  { id: "animal-messenger", name: "Animal Messenger", level: 2, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "24 hours", ritual: true, classes: ["bard", "druid", "ranger"] },
  { id: "animal-shapes", name: "Animal Shapes", level: 8, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Up to 24 hours", classes: ["druid"] },
  { id: "animate-dead", name: "Animate Dead", level: 3, school: "Necromancy", castingTime: "1 minute", range: "10 feet", duration: "Instantaneous", classes: ["cleric", "wizard"] },
  { id: "animate-objects", name: "Animate Objects", level: 5, school: "Transmutation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "antilife-shell", name: "Antilife Shell", level: 5, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["druid"] },
  { id: "antimagic-field", name: "Antimagic Field", level: 8, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["cleric", "wizard"] },
  { id: "antipathy-sympathy", name: "Antipathy/Sympathy", level: 8, school: "Enchantment", castingTime: "1 hour", range: "60 feet", duration: "10 days", classes: ["druid", "wizard"] },
  { id: "arcane-eye", name: "Arcane Eye", level: 4, school: "Divination", castingTime: "1 action", range: "30 feet", duration: "Up to 1 hour", classes: ["cleric", "wizard"] },
  { id: "arcane-hand", name: "Arcane Hand", level: 5, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", classes: ["wizard"] },
  { id: "arcane-lock", name: "Arcane Lock", level: 2, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Until dispelled", classes: ["wizard"] },
  { id: "arcane-sword", name: "Arcane Sword", level: 7, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", requiresAttackRoll: true, damageDice: "3d10", damageType: "Force", classes: ["bard", "wizard"] },
  { id: "arcanists-magic-aura", name: "Arcanist's Magic Aura", level: 2, school: "Illusion", castingTime: "1 action", range: "Touch", duration: "24 hours", classes: ["wizard"] },
  { id: "astral-projection", name: "Astral Projection", level: 9, school: "Necromancy", castingTime: "1 hour", range: "10 feet", duration: "Special", classes: ["cleric", "warlock", "wizard"] },
  { id: "augury", name: "Augury", level: 2, school: "Divination", castingTime: "1 minute", range: "Self", duration: "Instantaneous", ritual: true, classes: ["cleric"] },
  { id: "awaken", name: "Awaken", level: 5, school: "Transmutation", castingTime: "8 hours", range: "Touch", duration: "Instantaneous", classes: ["bard", "druid"] },
  { id: "bane", name: "Bane", level: 1, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "cha", classes: ["bard", "cleric"] },
  { id: "banishment", name: "Banishment", level: 4, school: "Abjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "cha", classes: ["cleric", "paladin", "sorcerer", "warlock", "wizard"] },
  { id: "barkskin", name: "Barkskin", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["druid", "ranger"] },
  { id: "beacon-of-hope", name: "Beacon of Hope", level: 3, school: "Abjuration", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", classes: ["cleric"] },
  { id: "bestow-curse", name: "Bestow Curse", level: 3, school: "Necromancy", castingTime: "1 action", range: "Touch", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "cleric", "wizard"] },
  { id: "black-tentacles", name: "Black Tentacles", level: 4, school: "Conjuration", castingTime: "1 action", range: "90 feet", duration: "Up to 1 minute", saveAbility: "dex", damageDice: "3d6", damageType: "Bludgeoning", classes: ["wizard"] },
  { id: "blade-barrier", name: "Blade Barrier", level: 6, school: "Evocation", castingTime: "1 action", range: "90 feet", duration: "Up to 10 minutes", saveAbility: "dex", damageDice: "6d10", damageType: "Slashing", classes: ["cleric"] },
  { id: "bless", name: "Bless", level: 1, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", classes: ["cleric", "paladin"] },
  { id: "blight", name: "Blight", level: 4, school: "Necromancy", castingTime: "1 action", range: "30 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "8d8", damageType: "Necrotic", classes: ["druid", "sorcerer", "warlock", "wizard"] },
  { id: "blindness-deafness", name: "Blindness/Deafness", level: 2, school: "Necromancy", castingTime: "1 action", range: "30 feet", duration: "1 minute", saveAbility: "con", classes: ["bard", "cleric", "sorcerer", "wizard"] },
  { id: "blink", name: "Blink", level: 3, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "1 minute", classes: ["sorcerer", "wizard"] },
  { id: "blur", name: "Blur", level: 2, school: "Illusion", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", classes: ["sorcerer", "wizard"] },
  { id: "branding-smite", name: "Branding Smite", level: 2, school: "Evocation", castingTime: "1 bonus action", range: "Self", duration: "Up to 1 minute", damageDice: "2d6", damageType: "Radiant", classes: ["paladin"] },
  { id: "burning-hands", name: "Burning Hands", level: 1, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Instantaneous", saveAbility: "dex", damageDice: "3d6", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "call-lightning", name: "Call Lightning", level: 3, school: "Conjuration", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", damageDice: "3d10", damageType: "Lightning", classes: ["druid"] },
  { id: "calm-emotions", name: "Calm Emotions", level: 2, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "cha", classes: ["bard", "cleric"] },
  { id: "chain-lightning", name: "Chain Lightning", level: 6, school: "Evocation", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "10d8", damageType: "Lightning", classes: ["sorcerer", "wizard"] },
  { id: "charm-person", name: "Charm Person", level: 1, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "1 hour", saveAbility: "wis", classes: ["bard", "druid", "sorcerer", "warlock", "wizard"] },
  { id: "chill-touch", name: "Chill Touch", level: 0, school: "Necromancy", castingTime: "1 action", range: "120 feet", duration: "1 round", requiresAttackRoll: true, damageDice: "1d8", damageType: "Necrotic", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "circle-of-death", name: "Circle of Death", level: 6, school: "Necromancy", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "8d6", damageType: "Necrotic", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "clairvoyance", name: "Clairvoyance", level: 3, school: "Divination", castingTime: "10 minutes", range: "1 mile", duration: "Up to 10 minutes", classes: ["bard", "cleric", "sorcerer", "wizard"] },
  { id: "clone", name: "Clone", level: 8, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", classes: ["wizard"] },
  { id: "cloudkill", name: "Cloudkill", level: 5, school: "Conjuration", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", saveAbility: "con", damageDice: "5d8", damageType: "Poison", classes: ["sorcerer", "wizard"] },
  { id: "color-spray", name: "Color Spray", level: 1, school: "Illusion", castingTime: "1 action", range: "Self", duration: "1 round", classes: ["sorcerer", "wizard"] },
  { id: "command", name: "Command", level: 1, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "1 round", saveAbility: "wis", classes: ["cleric", "paladin"] },
  { id: "commune", name: "Commune", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "1 minute", ritual: true, classes: ["cleric"] },
  { id: "commune-with-nature", name: "Commune With Nature", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "Instantaneous", ritual: true, classes: ["druid", "ranger"] },
  { id: "comprehend-languages", name: "Comprehend Languages", level: 1, school: "Divination", castingTime: "1 action", range: "Self", duration: "1 hour", ritual: true, classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "compulsion", name: "Compulsion", level: 4, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard"] },
  { id: "cone-of-cold", name: "Cone of Cold", level: 5, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Instantaneous", saveAbility: "con", damageDice: "8d8", damageType: "Cold", classes: ["sorcerer", "wizard"] },
  { id: "confusion", name: "Confusion", level: 4, school: "Enchantment", castingTime: "1 action", range: "90 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "druid", "sorcerer", "wizard"] },
  { id: "conjure-animals", name: "Conjure Animals", level: 3, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 hour", classes: ["druid", "ranger"] },
  { id: "conjure-celestial", name: "Conjure Celestial", level: 7, school: "Conjuration", castingTime: "1 minute", range: "90 feet", duration: "Up to 1 hour", classes: ["cleric"] },
  { id: "conjure-elemental", name: "Conjure Elemental", level: 5, school: "Conjuration", castingTime: "1 minute", range: "90 feet", duration: "Up to 1 hour", classes: ["druid", "wizard"] },
  { id: "conjure-fey", name: "Conjure Fey", level: 6, school: "Conjuration", castingTime: "1 minute", range: "90 feet", duration: "Up to 1 hour", classes: ["druid", "warlock"] },
  { id: "conjure-minor-elementals", name: "Conjure Minor Elementals", level: 4, school: "Conjuration", castingTime: "1 minute", range: "90 feet", duration: "Up to 1 hour", classes: ["druid", "wizard"] },
  { id: "conjure-woodland-beings", name: "Conjure Woodland Beings", level: 4, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 hour", classes: ["druid", "ranger"] },
  { id: "contact-other-plane", name: "Contact Other Plane", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "1 minute", saveAbility: "int", ritual: true, classes: ["warlock", "wizard"] },
  { id: "contagion", name: "Contagion", level: 5, school: "Necromancy", castingTime: "1 action", range: "Touch", duration: "7 days", requiresAttackRoll: true, saveAbility: "con", classes: ["cleric", "druid"] },
  { id: "contingency", name: "Contingency", level: 6, school: "Evocation", castingTime: "10 minutes", range: "Self", duration: "10 days", classes: ["wizard"] },
  { id: "continual-flame", name: "Continual Flame", level: 2, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "Until dispelled", classes: ["cleric", "wizard"] },
  { id: "control-water", name: "Control Water", level: 4, school: "Transmutation", castingTime: "1 action", range: "300 feet", duration: "Up to 10 minutes", saveAbility: "str", damageDice: "2d8", damageType: "Bludgeoning", classes: ["cleric", "druid", "wizard"] },
  { id: "control-weather", name: "Control Weather", level: 8, school: "Transmutation", castingTime: "10 minutes", range: "Self", duration: "Up to 8 hours", classes: ["cleric", "druid", "wizard"] },
  { id: "counterspell", name: "Counterspell", level: 3, school: "Abjuration", castingTime: "1 reaction", range: "60 feet", duration: "Instantaneous", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "create-food-and-water", name: "Create Food and Water", level: 3, school: "Conjuration", castingTime: "1 action", range: "30 feet", duration: "Instantaneous", classes: ["cleric", "druid", "paladin"] },
  { id: "create-undead", name: "Create Undead", level: 6, school: "Necromancy", castingTime: "1 minute", range: "10 feet", duration: "Instantaneous", classes: ["cleric", "warlock", "wizard"] },
  { id: "create-or-destroy-water", name: "Create or Destroy Water", level: 1, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Instantaneous", classes: ["cleric", "druid"] },
  { id: "creation", name: "Creation", level: 5, school: "Illusion", castingTime: "1 minute", range: "30 feet", duration: "Special", classes: ["sorcerer", "wizard"] },
  { id: "cure-wounds", name: "Cure Wounds", level: 1, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric", "druid", "paladin", "ranger"] },
  { id: "dancing-lights", name: "Dancing Lights", level: 0, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "darkness", name: "Darkness", level: 2, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Up to 10 minutes", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "darkvision", name: "Darkvision", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "8 hours", classes: ["druid", "ranger", "sorcerer", "wizard"] },
  { id: "daylight", name: "Daylight", level: 3, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "1 hour", classes: ["cleric", "druid", "paladin", "ranger", "sorcerer"] },
  { id: "death-ward", name: "Death Ward", level: 4, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "8 hours", classes: ["cleric", "paladin"] },
  { id: "delayed-blast-fireball", name: "Delayed Blast Fireball", level: 7, school: "Evocation", castingTime: "1 action", range: "150 feet", duration: "Up to 1 minute", saveAbility: "dex", damageDice: "12d6", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "demiplane", name: "Demiplane", level: 8, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "1 hour", classes: ["warlock", "wizard"] },
  { id: "detect-evil-and-good", name: "Detect Evil and Good", level: 1, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 10 minutes", classes: ["cleric", "paladin"] },
  { id: "detect-magic", name: "Detect Magic", level: 1, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 10 minutes", ritual: true, classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"] },
  { id: "detect-poison-and-disease", name: "Detect Poison and Disease", level: 1, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 10 minutes", ritual: true, classes: ["cleric", "druid", "paladin", "ranger"] },
  { id: "detect-thoughts", name: "Detect Thoughts", level: 2, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "dimension-door", name: "Dimension Door", level: 4, school: "Conjuration", castingTime: "1 action", range: "500 feet", duration: "Instantaneous", damageDice: "4d6", damageType: "Force", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "disguise-self", name: "Disguise Self", level: 1, school: "Illusion", castingTime: "1 action", range: "Self", duration: "1 hour", classes: ["bard", "sorcerer", "wizard"] },
  { id: "disintegrate", name: "Disintegrate", level: 6, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "10d6 + 40", damageType: "Force", classes: ["sorcerer", "wizard"] },
  { id: "dispel-evil-and-good", name: "Dispel Evil and Good", level: 5, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", saveAbility: "cha", classes: ["cleric", "paladin"] },
  { id: "dispel-magic", name: "Dispel Magic", level: 3, school: "Abjuration", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", classes: ["bard", "cleric", "druid", "paladin", "sorcerer", "warlock", "wizard"] },
  { id: "divination", name: "Divination", level: 4, school: "Divination", castingTime: "1 action", range: "Self", duration: "Instantaneous", ritual: true, classes: ["druid"] },
  { id: "divine-favor", name: "Divine Favor", level: 1, school: "Evocation", castingTime: "1 bonus action", range: "Self", duration: "Up to 1 minute", damageDice: "1d4", damageType: "Radiant", classes: ["paladin"] },
  { id: "divine-word", name: "Divine Word", level: 7, school: "Evocation", castingTime: "1 bonus action", range: "30 feet", duration: "Instantaneous", saveAbility: "cha", classes: ["cleric"] },
  { id: "dominate-beast", name: "Dominate Beast", level: 4, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["druid", "sorcerer"] },
  { id: "dominate-monster", name: "Dominate Monster", level: 8, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Up to 1 hour", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "dominate-person", name: "Dominate Person", level: 5, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "sorcerer", "wizard"] },
  { id: "dream", name: "Dream", level: 5, school: "Illusion", castingTime: "1 minute", range: "Special", duration: "8 hours", saveAbility: "wis", damageDice: "3d6", damageType: "Psychic", classes: ["bard", "warlock", "wizard"] },
  { id: "druidcraft", name: "Druidcraft", level: 0, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Instantaneous", classes: ["druid"] },
  { id: "earthquake", name: "Earthquake", level: 8, school: "Evocation", castingTime: "1 action", range: "500 feet", duration: "Up to 1 minute", classes: ["cleric", "druid", "sorcerer"] },
  { id: "eldritch-blast", name: "Eldritch Blast", level: 0, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "1d10", damageType: "Force", classes: ["warlock"] },
  { id: "enhance-ability", name: "Enhance Ability", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["bard", "cleric", "druid", "sorcerer"] },
  { id: "enlarge-reduce", name: "Enlarge/Reduce", level: 2, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "con", classes: ["sorcerer", "wizard"] },
  { id: "entangle", name: "Entangle", level: 1, school: "Conjuration", castingTime: "1 action", range: "90 feet", duration: "Up to 1 minute", saveAbility: "str", classes: ["druid"] },
  { id: "enthrall", name: "Enthrall", level: 2, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "1 minute", saveAbility: "wis", classes: ["bard", "warlock"] },
  { id: "etherealness", name: "Etherealness", level: 7, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "8 hours", classes: ["bard", "cleric", "sorcerer", "warlock", "wizard"] },
  { id: "expeditious-retreat", name: "Expeditious Retreat", level: 1, school: "Transmutation", castingTime: "1 bonus action", range: "Self", duration: "Up to 10 minutes", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "eyebite", name: "Eyebite", level: 6, school: "Necromancy", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "fabricate", name: "Fabricate", level: 4, school: "Transmutation", castingTime: "10 minutes", range: "120 feet", duration: "Instantaneous", classes: ["wizard"] },
  { id: "faerie-fire", name: "Faerie Fire", level: 1, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "dex", classes: ["druid"] },
  { id: "faithful-hound", name: "Faithful Hound", level: 4, school: "Conjuration", castingTime: "1 action", range: "30 feet", duration: "8 hours", requiresAttackRoll: true, damageDice: "4d8", damageType: "Piercing", classes: ["wizard"] },
  { id: "false-life", name: "False Life", level: 1, school: "Necromancy", castingTime: "1 action", range: "Self", duration: "1 hour", classes: ["sorcerer", "wizard"] },
  { id: "fear", name: "Fear", level: 3, school: "Illusion", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "feather-fall", name: "Feather Fall", level: 1, school: "Transmutation", castingTime: "1 reaction", range: "60 feet", duration: "1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "feeblemind", name: "Feeblemind", level: 8, school: "Enchantment", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "int", damageDice: "4d6", damageType: "Psychic", classes: ["bard", "druid", "warlock", "wizard"] },
  { id: "find-familiar", name: "Find Familiar", level: 1, school: "Conjuration", castingTime: "1 hour", range: "10 feet", duration: "Instantaneous", ritual: true, classes: ["wizard"] },
  { id: "find-steed", name: "Find Steed", level: 2, school: "Conjuration", castingTime: "10 minutes", range: "30 feet", duration: "Instantaneous", classes: ["paladin"] },
  { id: "find-traps", name: "Find Traps", level: 2, school: "Divination", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", classes: ["cleric", "druid", "ranger"] },
  { id: "find-the-path", name: "Find the Path", level: 6, school: "Divination", castingTime: "1 minute", range: "Self", duration: "Up to 24 hours", classes: ["bard", "cleric", "druid"] },
  { id: "finger-of-death", name: "Finger of Death", level: 7, school: "Necromancy", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "7d8 + 30", damageType: "Necrotic", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "fire-bolt", name: "Fire Bolt", level: 0, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "1d10", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "fire-shield", name: "Fire Shield", level: 4, school: "Evocation", castingTime: "1 action", range: "Self", duration: "10 minutes", damageDice: "2d8", damageType: "Fire", classes: ["wizard"] },
  { id: "fire-storm", name: "Fire Storm", level: 7, school: "Evocation", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "7d10", damageType: "Fire", classes: ["cleric", "druid", "sorcerer"] },
  { id: "fireball", name: "Fireball", level: 3, school: "Evocation", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "8d6", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "flame-blade", name: "Flame Blade", level: 2, school: "Evocation", castingTime: "1 bonus action", range: "Self", duration: "Up to 10 minutes", damageDice: "3d6", damageType: "Fire", classes: ["druid"] },
  { id: "flame-strike", name: "Flame Strike", level: 5, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "4d6 + 4d6", damageType: "Fire", classes: ["cleric"] },
  { id: "flaming-sphere", name: "Flaming Sphere", level: 2, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", damageDice: "2d6", damageType: "Fire", classes: ["druid", "wizard"] },
  { id: "flesh-to-stone", name: "Flesh to Stone", level: 6, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "con", classes: ["warlock", "wizard"] },
  { id: "floating-disk", name: "Floating Disk", level: 1, school: "Conjuration", castingTime: "1 action", range: "30 feet", duration: "1 hour", ritual: true, classes: ["wizard"] },
  { id: "fly", name: "Fly", level: 3, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Up to 10 minutes", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "fog-cloud", name: "Fog Cloud", level: 1, school: "Conjuration", castingTime: "1 action", range: "120 feet", duration: "Up to 1 hour", classes: ["druid", "ranger", "sorcerer", "wizard"] },
  { id: "forbiddance", name: "Forbiddance", level: 6, school: "Abjuration", castingTime: "10 minutes", range: "Touch", duration: "24 hours", ritual: true, classes: ["cleric"] },
  { id: "forcecage", name: "Forcecage", level: 7, school: "Evocation", castingTime: "1 action", range: "100 feet", duration: "1 hour", classes: ["bard", "warlock", "wizard"] },
  { id: "foresight", name: "Foresight", level: 9, school: "Divination", castingTime: "1 minute", range: "Touch", duration: "8 hours", classes: ["bard", "druid", "warlock", "wizard"] },
  { id: "freedom-of-movement", name: "Freedom of Movement", level: 4, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["bard", "cleric", "druid", "ranger"] },
  { id: "freezing-sphere", name: "Freezing Sphere", level: 6, school: "Evocation", castingTime: "1 action", range: "300 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "10d6", damageType: "Cold", classes: ["wizard"] },
  { id: "gaseous-form", name: "Gaseous Form", level: 3, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "gate", name: "Gate", level: 9, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", classes: ["cleric", "sorcerer", "wizard"] },
  { id: "geas", name: "Geas", level: 5, school: "Enchantment", castingTime: "1 minute", range: "60 feet", duration: "30 days", saveAbility: "wis", classes: ["bard", "cleric", "druid", "paladin", "wizard"] },
  { id: "gentle-repose", name: "Gentle Repose", level: 2, school: "Necromancy", castingTime: "1 action", range: "Touch", duration: "10 days", ritual: true, classes: ["cleric", "wizard"] },
  { id: "giant-insect", name: "Giant Insect", level: 4, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Up to 10 minutes", classes: ["druid"] },
  { id: "glibness", name: "Glibness", level: 8, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "1 hour", classes: ["bard", "warlock"] },
  { id: "globe-of-invulnerability", name: "Globe of Invulnerability", level: 6, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", classes: ["sorcerer", "wizard"] },
  { id: "glyph-of-warding", name: "Glyph of Warding", level: 3, school: "Abjuration", castingTime: "1 hour", range: "Touch", duration: "Until dispelled", classes: ["bard", "cleric", "wizard"] },
  { id: "goodberry", name: "Goodberry", level: 1, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["druid", "ranger"] },
  { id: "grease", name: "Grease", level: 1, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "1 minute", saveAbility: "dex", classes: ["wizard"] },
  { id: "greater-invisibility", name: "Greater Invisibility", level: 4, school: "Illusion", castingTime: "1 action", range: "Touch", duration: "Up to 1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "greater-restoration", name: "Greater Restoration", level: 5, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric", "druid"] },
  { id: "guardian-of-faith", name: "Guardian of Faith", level: 4, school: "Conjuration", castingTime: "1 action", range: "30 feet", duration: "8 hours", saveAbility: "dex", damageDice: "20", damageType: "Radiant", classes: ["cleric"] },
  { id: "guards-and-wards", name: "Guards and Wards", level: 6, school: "Abjuration", castingTime: "10 minutes", range: "Touch", duration: "24 hours", classes: ["bard", "wizard"] },
  { id: "guidance", name: "Guidance", level: 0, school: "Divination", castingTime: "1 action", range: "Touch", duration: "Up to 1 minute", classes: ["cleric", "druid"] },
  { id: "guiding-bolt", name: "Guiding Bolt", level: 1, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "1 round", requiresAttackRoll: true, damageDice: "4d6", damageType: "Radiant", classes: ["cleric"] },
  { id: "gust-of-wind", name: "Gust of Wind", level: 2, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", saveAbility: "str", classes: ["druid", "sorcerer", "wizard"] },
  { id: "hallow", name: "Hallow", level: 5, school: "Evocation", castingTime: "24 hours", range: "Touch", duration: "Until dispelled", saveAbility: "cha", classes: ["cleric"] },
  { id: "hallucinatory-terrain", name: "Hallucinatory Terrain", level: 4, school: "Illusion", castingTime: "10 minutes", range: "300 feet", duration: "24 hours", classes: ["bard", "druid", "warlock", "wizard"] },
  { id: "harm", name: "Harm", level: 6, school: "Necromancy", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "14d6", damageType: "Necrotic", classes: ["cleric"] },
  { id: "haste", name: "Haste", level: 3, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", classes: ["sorcerer", "wizard"] },
  { id: "heal", name: "Heal", level: 6, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["cleric", "druid"] },
  { id: "healing-word", name: "Healing Word", level: 1, school: "Evocation", castingTime: "1 bonus action", range: "60 feet", duration: "Instantaneous", classes: ["bard", "cleric", "druid"] },
  { id: "heat-metal", name: "Heat Metal", level: 2, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "con", damageDice: "2d8", damageType: "Fire", classes: ["bard", "druid"] },
  { id: "hellish-rebuke", name: "Hellish Rebuke", level: 1, school: "Evocation", castingTime: "1 reaction", range: "60 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "2d10", damageType: "Fire", classes: ["warlock"] },
  { id: "heroes-feast", name: "Heroes' Feast", level: 6, school: "Conjuration", castingTime: "10 minutes", range: "30 feet", duration: "Instantaneous", classes: ["cleric", "druid"] },
  { id: "heroism", name: "Heroism", level: 1, school: "Enchantment", castingTime: "1 action", range: "Touch", duration: "Up to 1 minute", classes: ["bard", "paladin"] },
  { id: "hideous-laughter", name: "Hideous Laughter", level: 1, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "wizard"] },
  { id: "hold-monster", name: "Hold Monster", level: 5, school: "Enchantment", castingTime: "1 action", range: "90 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "hold-person", name: "Hold Person", level: 2, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"] },
  { id: "holy-aura", name: "Holy Aura", level: 8, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", classes: ["cleric"] },
  { id: "hunters-mark", name: "Hunter's Mark", level: 1, school: "Divination", castingTime: "1 bonus action", range: "90 feet", duration: "Up to 1 hour", classes: ["ranger"] },
  { id: "hypnotic-pattern", name: "Hypnotic Pattern", level: 3, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "ice-storm", name: "Ice Storm", level: 4, school: "Evocation", castingTime: "1 action", range: "300 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "2d8 + 4d6", damageType: "Bludgeoning", classes: ["druid", "sorcerer", "wizard"] },
  { id: "identify", name: "Identify", level: 1, school: "Divination", castingTime: "1 minute", range: "Touch", duration: "Instantaneous", ritual: true, classes: ["bard", "wizard"] },
  { id: "illusory-script", name: "Illusory Script", level: 1, school: "Illusion", castingTime: "1 minute", range: "Touch", duration: "10 days", ritual: true, classes: ["bard", "warlock", "wizard"] },
  { id: "imprisonment", name: "Imprisonment", level: 9, school: "Abjuration", castingTime: "1 minute", range: "30 feet", duration: "Until dispelled", saveAbility: "wis", classes: ["warlock", "wizard"] },
  { id: "incendiary-cloud", name: "Incendiary Cloud", level: 8, school: "Conjuration", castingTime: "1 action", range: "150 feet", duration: "Up to 1 minute", saveAbility: "dex", damageDice: "10d8", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "inflict-wounds", name: "Inflict Wounds", level: 1, school: "Necromancy", castingTime: "1 action", range: "Touch", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "3d10", damageType: "Necrotic", classes: ["cleric"] },
  { id: "insect-plague", name: "Insect Plague", level: 5, school: "Conjuration", castingTime: "1 action", range: "300 feet", duration: "Up to 10 minutes", saveAbility: "con", damageDice: "4d10", damageType: "Piercing", classes: ["cleric", "druid", "sorcerer"] },
  { id: "instant-summons", name: "Instant Summons", level: 6, school: "Conjuration", castingTime: "1 minute", range: "Touch", duration: "Until dispelled", ritual: true, classes: ["wizard"] },
  { id: "invisibility", name: "Invisibility", level: 2, school: "Illusion", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "irresistible-dance", name: "Irresistible Dance", level: 6, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", classes: ["bard", "wizard"] },
  { id: "jump", name: "Jump", level: 1, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 minute", classes: ["druid", "ranger", "sorcerer", "wizard"] },
  { id: "knock", name: "Knock", level: 2, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["bard", "sorcerer", "wizard"] },
  { id: "legend-lore", name: "Legend Lore", level: 5, school: "Divination", castingTime: "10 minutes", range: "Self", duration: "Instantaneous", classes: ["bard", "cleric", "wizard"] },
  { id: "lesser-restoration", name: "Lesser Restoration", level: 2, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric", "druid", "paladin", "ranger"] },
  { id: "levitate", name: "Levitate", level: 2, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Up to 10 minutes", classes: ["sorcerer", "wizard"] },
  { id: "light", name: "Light", level: 0, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "1 hour", saveAbility: "dex", classes: ["bard", "cleric", "sorcerer", "wizard"] },
  { id: "lightning-bolt", name: "Lightning Bolt", level: 3, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Instantaneous", saveAbility: "dex", damageDice: "8d6", damageType: "Lightning", classes: ["sorcerer", "wizard"] },
  { id: "locate-animals-or-plants", name: "Locate Animals or Plants", level: 2, school: "Divination", castingTime: "1 action", range: "Self", duration: "Instantaneous", ritual: true, classes: ["bard", "druid", "ranger"] },
  { id: "locate-creature", name: "Locate Creature", level: 4, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["bard", "cleric", "druid", "paladin", "ranger", "wizard"] },
  { id: "locate-object", name: "Locate Object", level: 2, school: "Divination", castingTime: "1 action", range: "Self", duration: "Up to 10 minutes", classes: ["bard", "cleric", "druid", "paladin", "ranger", "wizard"] },
  { id: "longstrider", name: "Longstrider", level: 1, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["bard", "druid", "ranger", "wizard"] },
  { id: "mage-armor", name: "Mage Armor", level: 1, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "8 hours", classes: ["sorcerer", "wizard"] },
  { id: "mage-hand", name: "Mage Hand", level: 0, school: "Conjuration", castingTime: "1 action", range: "30 feet", duration: "1 minute", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "magic-circle", name: "Magic Circle", level: 3, school: "Abjuration", castingTime: "1 minute", range: "10 feet", duration: "1 hour", saveAbility: "cha", classes: ["cleric", "paladin", "warlock", "wizard"] },
  { id: "magic-jar", name: "Magic Jar", level: 6, school: "Necromancy", castingTime: "1 minute", range: "Self", duration: "Until dispelled", saveAbility: "cha", classes: ["wizard"] },
  { id: "magic-missile", name: "Magic Missile", level: 1, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", damageDice: "3d4 + 3", damageType: "Force", classes: ["sorcerer", "wizard"] },
  { id: "magic-mouth", name: "Magic Mouth", level: 2, school: "Illusion", castingTime: "1 minute", range: "30 feet", duration: "Until dispelled", ritual: true, classes: ["bard", "wizard"] },
  { id: "magic-weapon", name: "Magic Weapon", level: 2, school: "Transmutation", castingTime: "1 bonus action", range: "Touch", duration: "Up to 1 hour", classes: ["paladin", "wizard"] },
  { id: "magnificent-mansion", name: "Magnificent Mansion", level: 7, school: "Conjuration", castingTime: "1 minute", range: "300 feet", duration: "24 hours", classes: ["bard", "wizard"] },
  { id: "major-image", name: "Major Image", level: 3, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "mass-cure-wounds", name: "Mass Cure Wounds", level: 5, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["bard", "cleric", "druid"] },
  { id: "mass-heal", name: "Mass Heal", level: 9, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["cleric"] },
  { id: "mass-healing-word", name: "Mass Healing Word", level: 3, school: "Evocation", castingTime: "1 bonus action", range: "60 feet", duration: "Instantaneous", classes: ["cleric"] },
  { id: "mass-suggestion", name: "Mass Suggestion", level: 6, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "24 hours", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "maze", name: "Maze", level: 8, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 10 minutes", classes: ["wizard"] },
  { id: "meld-into-stone", name: "Meld Into Stone", level: 3, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "8 hours", ritual: true, classes: ["cleric"] },
  { id: "mending", name: "Mending", level: 0, school: "Transmutation", castingTime: "1 minute", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric", "druid", "sorcerer", "wizard"] },
  { id: "message", name: "Message", level: 0, school: "Transmutation", castingTime: "1 action", range: "120 feet", duration: "1 round", classes: ["bard", "sorcerer", "wizard"] },
  { id: "meteor-swarm", name: "Meteor Swarm", level: 9, school: "Evocation", castingTime: "1 action", range: "1 mile", duration: "Instantaneous", saveAbility: "dex", damageDice: "20d6 + 20d6", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "mind-blank", name: "Mind Blank", level: 8, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "24 hours", classes: ["bard", "wizard"] },
  { id: "minor-illusion", name: "Minor Illusion", level: 0, school: "Illusion", castingTime: "1 action", range: "30 feet", duration: "1 minute", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "mirage-arcane", name: "Mirage Arcane", level: 7, school: "Illusion", castingTime: "10 minutes", range: "Sight", duration: "10 days", classes: ["bard", "druid", "wizard"] },
  { id: "mirror-image", name: "Mirror Image", level: 2, school: "Illusion", castingTime: "1 action", range: "Self", duration: "1 minute", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "mislead", name: "Mislead", level: 5, school: "Illusion", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["bard", "wizard"] },
  { id: "misty-step", name: "Misty Step", level: 2, school: "Conjuration", castingTime: "1 bonus action", range: "Self", duration: "Instantaneous", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "modify-memory", name: "Modify Memory", level: 5, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["bard", "wizard"] },
  { id: "moonbeam", name: "Moonbeam", level: 2, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "con", damageDice: "2d10", damageType: "Radiant", classes: ["druid"] },
  { id: "move-earth", name: "Move Earth", level: 6, school: "Transmutation", castingTime: "1 action", range: "120 feet", duration: "Up to 2 hours", classes: ["druid", "sorcerer", "wizard"] },
  { id: "nondetection", name: "Nondetection", level: 3, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "8 hours", classes: ["bard", "ranger", "wizard"] },
  { id: "pass-without-trace", name: "Pass Without Trace", level: 2, school: "Abjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["druid", "ranger"] },
  { id: "passwall", name: "Passwall", level: 5, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "1 hour", classes: ["wizard"] },
  { id: "phantasmal-killer", name: "Phantasmal Killer", level: 4, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "wis", damageDice: "4d10", damageType: "Psychic", classes: ["wizard"] },
  { id: "phantom-steed", name: "Phantom Steed", level: 3, school: "Illusion", castingTime: "1 minute", range: "30 feet", duration: "1 hour", ritual: true, classes: ["wizard"] },
  { id: "planar-ally", name: "Planar Ally", level: 6, school: "Conjuration", castingTime: "10 minutes", range: "60 feet", duration: "Instantaneous", classes: ["cleric"] },
  { id: "planar-binding", name: "Planar Binding", level: 5, school: "Abjuration", castingTime: "1 hour", range: "60 feet", duration: "24 hours", saveAbility: "cha", classes: ["bard", "cleric", "druid", "wizard"] },
  { id: "plane-shift", name: "Plane Shift", level: 7, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", requiresAttackRoll: true, saveAbility: "cha", classes: ["cleric", "druid", "sorcerer", "warlock", "wizard"] },
  { id: "plant-growth", name: "Plant Growth", level: 3, school: "Transmutation", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", classes: ["bard", "druid", "ranger"] },
  { id: "poison-spray", name: "Poison Spray", level: 0, school: "Conjuration", castingTime: "1 action", range: "10 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "1d12", damageType: "Poison", classes: ["druid", "sorcerer", "warlock", "wizard"] },
  { id: "polymorph", name: "Polymorph", level: 4, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Up to 1 hour", saveAbility: "wis", classes: ["bard", "druid", "sorcerer", "wizard"] },
  { id: "power-word-kill", name: "Power Word Kill", level: 9, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "power-word-stun", name: "Power Word Stun", level: 8, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "prayer-of-healing", name: "Prayer of Healing", level: 2, school: "Evocation", castingTime: "10 minutes", range: "30 feet", duration: "Instantaneous", classes: ["cleric"] },
  { id: "prestidigitation", name: "Prestidigitation", level: 0, school: "Transmutation", castingTime: "1 action", range: "10 feet", duration: "1 hour", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "prismatic-spray", name: "Prismatic Spray", level: 7, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Instantaneous", saveAbility: "dex", classes: ["sorcerer", "wizard"] },
  { id: "prismatic-wall", name: "Prismatic Wall", level: 9, school: "Abjuration", castingTime: "1 action", range: "60 feet", duration: "10 minutes", classes: ["wizard"] },
  { id: "private-sanctum", name: "Private Sanctum", level: 4, school: "Abjuration", castingTime: "10 minutes", range: "120 feet", duration: "24 hours", classes: ["wizard"] },
  { id: "produce-flame", name: "Produce Flame", level: 0, school: "Conjuration", castingTime: "1 action", range: "Self", duration: "10 minutes", requiresAttackRoll: true, damageDice: "1d8", damageType: "Fire", classes: ["druid"] },
  { id: "programmed-illusion", name: "Programmed Illusion", level: 6, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Until dispelled", classes: ["bard", "wizard"] },
  { id: "project-image", name: "Project Image", level: 7, school: "Illusion", castingTime: "1 action", range: "500 miles", duration: "Up to 24 hours", classes: ["bard", "wizard"] },
  { id: "protection-from-energy", name: "Protection From Energy", level: 3, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["cleric", "druid", "ranger", "sorcerer", "wizard"] },
  { id: "protection-from-evil-and-good", name: "Protection from Evil and Good", level: 1, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Up to 10 minutes", classes: ["cleric", "paladin", "warlock", "wizard"] },
  { id: "protection-from-poison", name: "Protection from Poison", level: 2, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["cleric", "druid", "paladin", "ranger"] },
  { id: "purify-food-and-drink", name: "Purify Food and Drink", level: 1, school: "Transmutation", castingTime: "1 action", range: "10 feet", duration: "Instantaneous", ritual: true, classes: ["cleric", "druid", "paladin"] },
  { id: "raise-dead", name: "Raise Dead", level: 5, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric", "paladin"] },
  { id: "ray-of-enfeeblement", name: "Ray of Enfeeblement", level: 2, school: "Necromancy", castingTime: "1 action", range: "60 feet", duration: "Up to 1 minute", requiresAttackRoll: true, saveAbility: "con", classes: ["warlock", "wizard"] },
  { id: "ray-of-frost", name: "Ray of Frost", level: 0, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "1d8", damageType: "Cold", classes: ["sorcerer", "wizard"] },
  { id: "regenerate", name: "Regenerate", level: 7, school: "Transmutation", castingTime: "1 minute", range: "Touch", duration: "1 hour", classes: ["bard", "cleric", "druid"] },
  { id: "reincarnate", name: "Reincarnate", level: 5, school: "Transmutation", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", classes: ["druid"] },
  { id: "remove-curse", name: "Remove Curse", level: 3, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["cleric", "paladin", "warlock", "wizard"] },
  { id: "resilient-sphere", name: "Resilient Sphere", level: 4, school: "Evocation", castingTime: "1 action", range: "30 feet", duration: "Up to 1 minute", saveAbility: "dex", classes: ["wizard"] },
  { id: "resistance", name: "Resistance", level: 0, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Up to 1 minute", classes: ["cleric", "druid"] },
  { id: "resurrection", name: "Resurrection", level: 7, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", classes: ["bard", "cleric"] },
  { id: "reverse-gravity", name: "Reverse Gravity", level: 7, school: "Transmutation", castingTime: "1 action", range: "100 feet", duration: "Up to 1 minute", saveAbility: "dex", classes: ["druid", "sorcerer", "wizard"] },
  { id: "revivify", name: "Revivify", level: 3, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["cleric", "paladin"] },
  { id: "rope-trick", name: "Rope Trick", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["wizard"] },
  { id: "sacred-flame", name: "Sacred Flame", level: 0, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "dex", damageDice: "1d8", damageType: "Radiant", classes: ["cleric"] },
  { id: "sanctuary", name: "Sanctuary", level: 1, school: "Abjuration", castingTime: "1 bonus action", range: "30 feet", duration: "1 minute", classes: ["cleric"] },
  { id: "scorching-ray", name: "Scorching Ray", level: 2, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Instantaneous", damageDice: "2d6", damageType: "Fire", classes: ["sorcerer", "wizard"] },
  { id: "scrying", name: "Scrying", level: 5, school: "Divination", castingTime: "10 minutes", range: "Self", duration: "Up to 10 minutes", saveAbility: "wis", classes: ["bard", "cleric", "druid", "warlock", "wizard"] },
  { id: "secret-chest", name: "Secret Chest", level: 4, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["wizard"] },
  { id: "see-invisibility", name: "See Invisibility", level: 2, school: "Divination", castingTime: "1 action", range: "Self", duration: "1 hour", classes: ["bard", "sorcerer", "wizard"] },
  { id: "seeming", name: "Seeming", level: 5, school: "Illusion", castingTime: "1 action", range: "30 feet", duration: "8 hours", classes: ["bard", "sorcerer", "wizard"] },
  { id: "sending", name: "Sending", level: 3, school: "Evocation", castingTime: "1 action", range: "Unlimited", duration: "1 round", classes: ["bard", "cleric", "wizard"] },
  { id: "sequester", name: "Sequester", level: 7, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Until dispelled", classes: ["wizard"] },
  { id: "shapechange", name: "Shapechange", level: 9, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "Up to 1 hour", classes: ["druid", "wizard"] },
  { id: "shatter", name: "Shatter", level: 2, school: "Evocation", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "3d8", damageType: "Thunder", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "shield", name: "Shield", level: 1, school: "Abjuration", castingTime: "1 reaction", range: "Self", duration: "1 round", classes: ["sorcerer", "wizard"] },
  { id: "shield-of-faith", name: "Shield of Faith", level: 1, school: "Abjuration", castingTime: "1 bonus action", range: "60 feet", duration: "Up to 10 minutes", classes: ["cleric", "paladin"] },
  { id: "shillelagh", name: "Shillelagh", level: 0, school: "Transmutation", castingTime: "1 bonus action", range: "Touch", duration: "1 minute", classes: ["druid"] },
  { id: "shocking-grasp", name: "Shocking Grasp", level: 0, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "Instantaneous", requiresAttackRoll: true, damageDice: "1d8", damageType: "Lightning", classes: ["sorcerer", "wizard"] },
  { id: "silence", name: "Silence", level: 2, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", ritual: true, classes: ["bard", "cleric", "ranger"] },
  { id: "silent-image", name: "Silent Image", level: 1, school: "Illusion", castingTime: "1 action", range: "60 feet", duration: "Up to 10 minutes", classes: ["bard", "sorcerer", "wizard"] },
  { id: "simulacrum", name: "Simulacrum", level: 7, school: "Illusion", castingTime: "12 hours", range: "Touch", duration: "Until dispelled", classes: ["wizard"] },
  { id: "sleep", name: "Sleep", level: 1, school: "Enchantment", castingTime: "1 action", range: "90 feet", duration: "1 minute", classes: ["bard", "sorcerer", "wizard"] },
  { id: "sleet-storm", name: "Sleet Storm", level: 3, school: "Conjuration", castingTime: "1 action", range: "150 feet", duration: "Up to 1 minute", classes: ["druid", "sorcerer", "wizard"] },
  { id: "slow", name: "Slow", level: 3, school: "Transmutation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["sorcerer", "wizard"] },
  { id: "spare-the-dying", name: "Spare the Dying", level: 0, school: "Necromancy", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["cleric"] },
  { id: "speak-with-animals", name: "Speak with Animals", level: 1, school: "Divination", castingTime: "1 action", range: "Self", duration: "10 minutes", ritual: true, classes: ["bard", "druid", "ranger"] },
  { id: "speak-with-dead", name: "Speak with Dead", level: 3, school: "Necromancy", castingTime: "1 action", range: "10 feet", duration: "10 minutes", classes: ["bard", "cleric"] },
  { id: "speak-with-plants", name: "Speak with Plants", level: 3, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "10 minutes", classes: ["bard", "druid", "ranger"] },
  { id: "spider-climb", name: "Spider Climb", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["sorcerer", "warlock", "wizard"] },
  { id: "spike-growth", name: "Spike Growth", level: 2, school: "Transmutation", castingTime: "1 action", range: "150 feet", duration: "Up to 10 minutes", classes: ["druid", "ranger"] },
  { id: "spirit-guardians", name: "Spirit Guardians", level: 3, school: "Conjuration", castingTime: "1 action", range: "Self", duration: "Up to 10 minutes", classes: ["cleric"] },
  { id: "spiritual-weapon", name: "Spiritual Weapon", level: 2, school: "Evocation", castingTime: "1 bonus action", range: "60 feet", duration: "1 minute", requiresAttackRoll: true, damageDice: "1d8 + MOD", damageType: "Force", classes: ["cleric"] },
  { id: "stinking-cloud", name: "Stinking Cloud", level: 3, school: "Conjuration", castingTime: "1 action", range: "90 feet", duration: "Up to 1 minute", saveAbility: "con", classes: ["bard", "sorcerer", "wizard"] },
  { id: "stone-shape", name: "Stone Shape", level: 4, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "Instantaneous", classes: ["cleric", "druid", "wizard"] },
  { id: "stoneskin", name: "Stoneskin", level: 4, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "Up to 1 hour", classes: ["druid", "ranger", "sorcerer", "wizard"] },
  { id: "storm-of-vengeance", name: "Storm of Vengeance", level: 9, school: "Conjuration", castingTime: "1 action", range: "Sight", duration: "Up to 1 minute", saveAbility: "con", damageDice: "2d6", damageType: "Thunder", classes: ["druid"] },
  { id: "suggestion", name: "Suggestion", level: 2, school: "Enchantment", castingTime: "1 action", range: "30 feet", duration: "Up to 8 hours", saveAbility: "wis", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "sunbeam", name: "Sunbeam", level: 6, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", saveAbility: "con", damageDice: "6d8", damageType: "Radiant", classes: ["druid", "sorcerer", "wizard"] },
  { id: "sunburst", name: "Sunburst", level: 8, school: "Evocation", castingTime: "1 action", range: "150 feet", duration: "Instantaneous", saveAbility: "con", damageDice: "12d6", damageType: "Radiant", classes: ["druid", "sorcerer", "wizard"] },
  { id: "symbol", name: "Symbol", level: 7, school: "Abjuration", castingTime: "1 minute", range: "Touch", duration: "Until dispelled", classes: ["bard", "cleric", "wizard"] },
  { id: "telekinesis", name: "Telekinesis", level: 5, school: "Transmutation", castingTime: "1 action", range: "60 feet", duration: "Up to 10 minutes", classes: ["sorcerer", "wizard"] },
  { id: "telepathic-bond", name: "Telepathic Bond", level: 5, school: "Divination", castingTime: "1 action", range: "30 feet", duration: "1 hour", ritual: true, classes: ["wizard"] },
  { id: "teleport", name: "Teleport", level: 7, school: "Conjuration", castingTime: "1 action", range: "10 feet", duration: "Instantaneous", classes: ["bard", "sorcerer", "wizard"] },
  { id: "teleportation-circle", name: "Teleportation Circle", level: 5, school: "Conjuration", castingTime: "1 minute", range: "10 feet", duration: "1 round", classes: ["bard", "sorcerer", "wizard"] },
  { id: "thaumaturgy", name: "Thaumaturgy", level: 0, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "1 minute", classes: ["cleric"] },
  { id: "thunderwave", name: "Thunderwave", level: 1, school: "Evocation", castingTime: "1 action", range: "Self", duration: "Instantaneous", saveAbility: "con", damageDice: "2d8", damageType: "Thunder", classes: ["bard", "druid", "sorcerer", "wizard"] },
  { id: "time-stop", name: "Time Stop", level: 9, school: "Transmutation", castingTime: "1 action", range: "Self", duration: "Instantaneous", classes: ["sorcerer", "wizard"] },
  { id: "tiny-hut", name: "Tiny Hut", level: 3, school: "Evocation", castingTime: "1 minute", range: "Self", duration: "8 hours", ritual: true, classes: ["bard", "wizard"] },
  { id: "tongues", name: "Tongues", level: 3, school: "Divination", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["bard", "cleric", "sorcerer", "warlock", "wizard"] },
  { id: "transport-via-plants", name: "Transport via Plants", level: 6, school: "Conjuration", castingTime: "1 action", range: "10 feet", duration: "1 round", classes: ["druid"] },
  { id: "tree-stride", name: "Tree Stride", level: 5, school: "Conjuration", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", classes: ["druid", "ranger"] },
  { id: "true-polymorph", name: "True Polymorph", level: 9, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "Up to 1 hour", classes: ["bard", "warlock", "wizard"] },
  { id: "true-resurrection", name: "True Resurrection", level: 9, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", classes: ["cleric", "druid"] },
  { id: "true-seeing", name: "True Seeing", level: 6, school: "Divination", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["bard", "cleric", "sorcerer", "warlock", "wizard"] },
  { id: "true-strike", name: "True Strike", level: 0, school: "Divination", castingTime: "1 action", range: "30 feet", duration: "Up to 1 round", classes: ["bard", "sorcerer", "warlock", "wizard"] },
  { id: "unseen-servant", name: "Unseen Servant", level: 1, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "1 hour", ritual: true, classes: ["bard", "warlock", "wizard"] },
  { id: "vampiric-touch", name: "Vampiric Touch", level: 3, school: "Necromancy", castingTime: "1 action", range: "Self", duration: "Up to 1 minute", requiresAttackRoll: true, damageDice: "3d6", damageType: "Necrotic", classes: ["warlock", "wizard"] },
  { id: "vicious-mockery", name: "Vicious Mockery", level: 0, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "Instantaneous", saveAbility: "wis", damageDice: "1d4", damageType: "Psychic", classes: ["bard"] },
  { id: "wall-of-fire", name: "Wall of Fire", level: 4, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "dex", damageDice: "5d8", damageType: "Fire", classes: ["druid", "sorcerer", "wizard"] },
  { id: "wall-of-force", name: "Wall of Force", level: 5, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", classes: ["wizard"] },
  { id: "wall-of-ice", name: "Wall of Ice", level: 6, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", saveAbility: "dex", damageDice: "10d6", damageType: "Cold", classes: ["wizard"] },
  { id: "wall-of-stone", name: "Wall of Stone", level: 5, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", classes: ["druid", "sorcerer", "wizard"] },
  { id: "wall-of-thorns", name: "Wall of Thorns", level: 6, school: "Conjuration", castingTime: "1 action", range: "120 feet", duration: "Up to 10 minutes", saveAbility: "dex", damageDice: "7d8", damageType: "Piercing", classes: ["druid"] },
  { id: "warding-bond", name: "Warding Bond", level: 2, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 hour", classes: ["cleric"] },
  { id: "water-breathing", name: "Water Breathing", level: 3, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "24 hours", ritual: true, classes: ["druid", "ranger", "sorcerer", "wizard"] },
  { id: "water-walk", name: "Water Walk", level: 3, school: "Transmutation", castingTime: "1 action", range: "30 feet", duration: "1 hour", ritual: true, classes: ["cleric", "druid", "ranger", "sorcerer"] },
  { id: "web", name: "Web", level: 2, school: "Conjuration", castingTime: "1 action", range: "60 feet", duration: "Up to 1 hour", classes: ["sorcerer", "wizard"] },
  { id: "weird", name: "Weird", level: 9, school: "Illusion", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "wis", classes: ["wizard"] },
  { id: "wind-walk", name: "Wind Walk", level: 6, school: "Transmutation", castingTime: "1 minute", range: "30 feet", duration: "8 hours", classes: ["druid"] },
  { id: "wind-wall", name: "Wind Wall", level: 3, school: "Evocation", castingTime: "1 action", range: "120 feet", duration: "Up to 1 minute", saveAbility: "str", damageDice: "3d8", damageType: "Bludgeoning", classes: ["druid", "ranger"] },
  { id: "wish", name: "Wish", level: 9, school: "Conjuration", castingTime: "1 action", range: "Self", duration: "Instantaneous", classes: ["sorcerer", "wizard"] },
  { id: "word-of-recall", name: "Word of Recall", level: 6, school: "Conjuration", castingTime: "1 action", range: "5 feet", duration: "Instantaneous", classes: ["cleric"] },
  { id: "zone-of-truth", name: "Zone of Truth", level: 2, school: "Enchantment", castingTime: "1 action", range: "60 feet", duration: "10 minutes", classes: ["bard", "cleric", "paladin"] },
];
