// SRD 5.1 magic items (CC-BY-4.0), sourced from the open 5e-bits/5e-database project.
// Names, category, and rarity only -- no rules text/prose reproduced. Used purely as an
// autocomplete list so players can pick an accurate item name; ability/AC effects are
// always entered manually per item since the SRD data has no structured numeric effects.
export interface SrdMagicItem {
  id: string;
  name: string;
  category: string;
  rarity: string;
}

export const SRD_MAGIC_ITEMS: SrdMagicItem[] = [
  { id: "adamantine-armor", name: "Adamantine Armor", category: "Armor", rarity: "Uncommon" },
  { id: "elemental-gem-air", name: "Air Elemental Gem", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "ammunition-1", name: "Ammunition, +1", category: "Ammunition", rarity: "Uncommon" },
  { id: "ammunition", name: "Ammunition, +1, +2, or +3", category: "Ammunition", rarity: "Varies" },
  { id: "ammunition-2", name: "Ammunition, +2", category: "Ammunition", rarity: "Rare" },
  { id: "ammunition-3", name: "Ammunition, +3", category: "Ammunition", rarity: "Very Rare" },
  { id: "amulet-of-health", name: "Amulet of Health", category: "Wondrous Items", rarity: "Rare" },
  { id: "amulet-of-proof-against-detection-and-location", name: "Amulet of Proof against Detection and Location", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "amulet-of-the-planes", name: "Amulet of the Planes", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "feather-token-anchor", name: "Anchor Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "animated-shield", name: "Animated Shield", category: "Armor", rarity: "Very Rare" },
  { id: "apparatus-of-the-crab", name: "Apparatus of the Crab", category: "Wondrous Items", rarity: "Legendary" },
  { id: "armor-of-invulnerability", name: "Armor of Invulnerability", category: "Armor", rarity: "Legendary" },
  { id: "armor-of-resistance", name: "Armor of Resistance", category: "Armor", rarity: "Rare" },
  { id: "armor-of-vulnerability", name: "Armor of Vulnerability", category: "Armor", rarity: "Rare" },
  { id: "armor-1", name: "Armor, +1", category: "Armor", rarity: "Rare" },
  { id: "armor", name: "Armor, +1, +2, or +3", category: "Armor", rarity: "Varies" },
  { id: "armor-2", name: "Armor, +2", category: "Armor", rarity: "Very Rare" },
  { id: "armor-3", name: "Armor, +3", category: "Armor", rarity: "Legendary" },
  { id: "arrow-of-slaying", name: "Arrow of Slaying", category: "Ammunition", rarity: "Very Rare" },
  { id: "arrow-catching-shield", name: "Arrow-Catching Shield", category: "Armor", rarity: "Rare" },
  { id: "bag-of-beans", name: "Bag of Beans", category: "Wondrous Items", rarity: "Rare" },
  { id: "bag-of-devouring", name: "Bag of Devouring", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "bag-of-holding", name: "Bag of Holding", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "bag-of-tricks", name: "Bag of Tricks", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "bead-of-force", name: "Bead of Force", category: "Wondrous Items", rarity: "Rare" },
  { id: "belt-of-giant-strength-cloud", name: "Belt of Cloud Giant Strength", category: "Wondrous Items", rarity: "Legendary" },
  { id: "belt-of-dwarvenkind", name: "Belt of Dwarvenkind", category: "Wondrous Items", rarity: "Rare" },
  { id: "belt-of-giant-strength-fire", name: "Belt of Fire Giant Strength", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "belt-of-giant-strength-frost", name: "Belt of Frost Giant Strength", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "belt-of-giant-strength", name: "Belt of Giant Strength", category: "Wondrous Items", rarity: "Varies" },
  { id: "belt-of-giant-strength-hill", name: "Belt of Hill Giant Strength", category: "Wondrous Items", rarity: "Rare" },
  { id: "belt-of-giant-strength-stone", name: "Belt of Stone Giant Strength", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "belt-of-giant-strength-storm", name: "Belt of Storm Giant Strength", category: "Wondrous Items", rarity: "Legendary" },
  { id: "berserker-axe", name: "Berserker Axe", category: "Weapon", rarity: "Rare" },
  { id: "feather-token-bird", name: "Bird Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "dragon-scale-mail-black", name: "Black Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "dragon-scale-mail-blue", name: "Blue Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "boots-of-elvenkind", name: "Boots of Elvenkind", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "boots-of-levitation", name: "Boots of Levitation", category: "Wondrous Items", rarity: "Rare" },
  { id: "boots-of-speed", name: "Boots of Speed", category: "Wondrous Items", rarity: "Rare" },
  { id: "boots-of-striding-and-springing", name: "Boots of Striding and Springing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "boots-of-the-winterlands", name: "Boots of the Winterlands", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "bowl-of-commanding-water-elementals", name: "Bowl of Commanding Water Elementals", category: "Wondrous Items", rarity: "Rare" },
  { id: "bracers-of-archery", name: "Bracers of Archery", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "bracers-of-defense", name: "Bracers of Defense", category: "Wondrous Items", rarity: "Rare" },
  { id: "dragon-scale-mail-brass", name: "Brass Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "horn-of-valhalla-brass", name: "Brass Horn of Valhalla", category: "Wondrous Items", rarity: "Rare" },
  { id: "brazier-of-commanding-fire-elementals", name: "Brazier of Commanding Fire Elementals", category: "Wondrous Items", rarity: "Rare" },
  { id: "dragon-scale-mail-bronze", name: "Bronze Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "figurine-of-wondrous-power-bronze-griffon", name: "Bronze Griffon Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "horn-of-valhalla-bronze", name: "Bronze Horn of Valhalla", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "brooch-of-shielding", name: "Brooch of Shielding", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "broom-of-flying", name: "Broom of Flying", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "candle-of-invocation", name: "Candle of Invocation", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "cape-of-the-mountebank", name: "Cape of the Mountebank", category: "Wondrous Items", rarity: "Rare" },
  { id: "carpet-of-flying", name: "Carpet of Flying", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "carpet-of-flying-3x5", name: "Carpet of Flying (3 ft. × 5 ft.)", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "carpet-of-flying-4x6", name: "Carpet of Flying (4 ft. × 6 ft.)", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "carpet-of-flying-5x7", name: "Carpet of Flying (5 ft. × 7 ft.)", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "carpet-of-flying-6x9", name: "Carpet of Flying (6 ft. × 9 ft.)", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "censer-of-controlling-air-elementals", name: "Censer of Controlling Air Elementals", category: "Wondrous Items", rarity: "Rare" },
  { id: "chime-of-opening", name: "Chime of Opening", category: "Wondrous Items", rarity: "Rare" },
  { id: "circlet-of-blasting", name: "Circlet of Blasting", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "cloak-of-arachnida", name: "Cloak of Arachnida", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "cloak-of-displacement", name: "Cloak of Displacement", category: "Wondrous Items", rarity: "Rare" },
  { id: "cloak-of-elvenkind", name: "Cloak of Elvenkind", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "cloak-of-protection", name: "Cloak of Protection", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "cloak-of-the-bat", name: "Cloak of the Bat", category: "Wondrous Items", rarity: "Rare" },
  { id: "cloak-of-the-manta-ray", name: "Cloak of the Manta Ray", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dragon-scale-mail-copper", name: "Copper Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "crystal-ball", name: "Crystal Ball", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "crystal-ball-of-mind-reading", name: "Crystal Ball of Mind Reading", category: "Wondrous Items", rarity: "Legendary" },
  { id: "crystal-ball-of-telepathy", name: "Crystal Ball of Telepathy", category: "Wondrous Items", rarity: "Legendary" },
  { id: "crystal-ball-of-true-seeing", name: "Crystal Ball of True Seeing", category: "Wondrous Items", rarity: "Legendary" },
  { id: "cube-of-force", name: "Cube of Force", category: "Wondrous Items", rarity: "Rare" },
  { id: "cubic-gate", name: "Cubic Gate", category: "Wondrous Items", rarity: "Legendary" },
  { id: "dagger-of-venom", name: "Dagger of Venom", category: "Weapon", rarity: "Rare" },
  { id: "dancing-sword", name: "Dancing Sword", category: "Weapon", rarity: "Very Rare" },
  { id: "decanter-of-endless-water", name: "Decanter of Endless Water", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "deck-of-illusions", name: "Deck of Illusions", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "deck-of-many-things", name: "Deck of Many Things", category: "Wondrous Items", rarity: "Legendary" },
  { id: "defender", name: "Defender", category: "Weapon", rarity: "Legendary" },
  { id: "demon-armor", name: "Demon Armor", category: "Armor", rarity: "Very Rare" },
  { id: "dimensional-shackles", name: "Dimensional Shackles", category: "Wondrous Items", rarity: "Rare" },
  { id: "dragon-scale-mail", name: "Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "dragon-slayer", name: "Dragon Slayer", category: "Weapon", rarity: "Rare" },
  { id: "dust-of-disappearance", name: "Dust of Disappearance", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dust-of-dryness", name: "Dust of Dryness", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dust-of-sneezing-and-choking", name: "Dust of Sneezing and Choking", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dwarven-plate", name: "Dwarven Plate", category: "Armor", rarity: "Very Rare" },
  { id: "dwarven-thrower", name: "Dwarven Thrower", category: "Weapon", rarity: "Very Rare" },
  { id: "elemental-gem-earth", name: "Earth Elemental Gem", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "figurine-of-wondrous-power-ebony-fly", name: "Ebony Fly Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "efficient-quiver", name: "Efficient Quiver", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "efreeti-bottle", name: "Efreeti Bottle", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "elemental-gem", name: "Elemental Gem", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "elven-chain", name: "Elven Chain", category: "Armor", rarity: "Rare" },
  { id: "eversmoking-bottle", name: "Eversmoking Bottle", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "eyes-of-charming", name: "Eyes of Charming", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "eyes-of-minute-seeing", name: "Eyes of Minute Seeing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "eyes-of-the-eagle", name: "Eyes of the Eagle", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "feather-token-fan", name: "Fan Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "feather-token", name: "Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "figurine-of-wondrous-power", name: "Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Varies" },
  { id: "elemental-gem-fire", name: "Fire Elemental Gem", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "flame-tongue", name: "Flame Tongue", category: "Weapon", rarity: "Rare" },
  { id: "folding-boat", name: "Folding Boat", category: "Wondrous Items", rarity: "Rare" },
  { id: "frost-brand", name: "Frost Brand", category: "Weapon", rarity: "Very Rare" },
  { id: "gauntlets-of-ogre-power", name: "Gauntlets of Ogre Power", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "gem-of-brightness", name: "Gem of Brightness", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "gem-of-seeing", name: "Gem of Seeing", category: "Wondrous Items", rarity: "Rare" },
  { id: "giant-slayer", name: "Giant Slayer", category: "Weapon", rarity: "Rare" },
  { id: "glamoured-studded-leather-armor", name: "Glamoured Studded Leather Armor", category: "Armor", rarity: "Rare" },
  { id: "gloves-of-missile-snaring", name: "Gloves of Missile Snaring", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "gloves-of-swimming-and-climbing", name: "Gloves of Swimming and Climbing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "goggles-of-night", name: "Goggles of Night", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dragon-scale-mail-gold", name: "Gold Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "figurine-of-wondrous-power-golden-lions", name: "Golden Lions Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "bag-of-tricks-gray", name: "Gray Bag of Tricks", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "dragon-scale-mail-green", name: "Green Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "hammer-of-thunderbolts", name: "Hammer of Thunderbolts", category: "Weapon", rarity: "Legendary" },
  { id: "handy-haversack", name: "Handy Haversack", category: "Wondrous Items", rarity: "Rare" },
  { id: "hat-of-disguise", name: "Hat of Disguise", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "headband-of-intellect", name: "Headband of Intellect", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "helm-of-brilliance", name: "Helm of Brilliance", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "helm-of-comprehending-languages", name: "Helm of Comprehending Languages", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "helm-of-telepathy", name: "Helm of Telepathy", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "helm-of-teleportation", name: "Helm of Teleportation", category: "Wondrous Items", rarity: "Rare" },
  { id: "holy-avenger", name: "Holy Avenger", category: "Weapon", rarity: "Legendary" },
  { id: "horn-of-blasting", name: "Horn of Blasting", category: "Wondrous Items", rarity: "Rare" },
  { id: "horn-of-valhalla", name: "Horn of Valhalla", category: "Wondrous Items", rarity: "Varies" },
  { id: "horseshoes-of-speed", name: "Horseshoes of Speed", category: "Wondrous Items", rarity: "Rare" },
  { id: "horseshoes-of-a-zephyr", name: "Horseshoes of a Zephyr", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "immovable-rod", name: "Immovable Rod", category: "Rod", rarity: "Uncommon" },
  { id: "instant-fortress", name: "Instant Fortress", category: "Wondrous Items", rarity: "Rare" },
  { id: "ioun-stone", name: "Ioun Stone", category: "Wondrous Items", rarity: "Varies" },
  { id: "ioun-stone-of-absorption", name: "Ioun Stone of Absorption", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-agility", name: "Ioun Stone of Agility", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-awareness", name: "Ioun Stone of Awareness", category: "Wondrous Items", rarity: "Rare" },
  { id: "ioun-stone-of-fortitude", name: "Ioun Stone of Fortitude", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-greater-absorption", name: "Ioun Stone of Greater Absorption", category: "Wondrous Items", rarity: "Legendary" },
  { id: "ioun-stone-of-insight", name: "Ioun Stone of Insight", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-intellect", name: "Ioun Stone of Intellect", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-leadership", name: "Ioun Stone of Leadership", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-mastery", name: "Ioun Stone of Mastery", category: "Wondrous Items", rarity: "Legendary" },
  { id: "ioun-stone-of-protection", name: "Ioun Stone of Protection", category: "Wondrous Items", rarity: "Rare" },
  { id: "ioun-stone-of-regeneration", name: "Ioun Stone of Regeneration", category: "Wondrous Items", rarity: "Legendary" },
  { id: "ioun-stone-of-reserve", name: "Ioun Stone of Reserve", category: "Wondrous Items", rarity: "Rare" },
  { id: "ioun-stone-of-strength", name: "Ioun Stone of Strength", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "ioun-stone-of-sustenance", name: "Ioun Stone of Sustenance", category: "Wondrous Items", rarity: "Rare" },
  { id: "iron-bands-of-binding", name: "Iron Bands of Binding", category: "Wondrous Items", rarity: "Rare" },
  { id: "iron-flask", name: "Iron Flask", category: "Wondrous Items", rarity: "Legendary" },
  { id: "horn-of-valhalla-iron", name: "Iron Horn of Valhalla", category: "Wondrous Items", rarity: "Legendary" },
  { id: "figurine-of-wondrous-power-ivory-goats", name: "Ivory Goats Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "javelin-of-lightning", name: "Javelin of Lightning", category: "Weapon", rarity: "Uncommon" },
  { id: "lantern-of-revealing", name: "Lantern of Revealing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "luck-blade", name: "Luck Blade", category: "Weapon", rarity: "Legendary" },
  { id: "mace-of-disruption", name: "Mace of Disruption", category: "Weapon", rarity: "Rare" },
  { id: "mace-of-smiting", name: "Mace of Smiting", category: "Weapon", rarity: "Rare" },
  { id: "mace-of-terror", name: "Mace of Terror", category: "Weapon", rarity: "Rare" },
  { id: "mantle-of-spell-resistance", name: "Mantle of Spell Resistance", category: "Wondrous Items", rarity: "Rare" },
  { id: "manual-of-bodily-health", name: "Manual of Bodily Health", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-golems-clay", name: "Manual of Clay Golems", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-golems-flesh", name: "Manual of Flesh Golems", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-gainful-exercise", name: "Manual of Gainful Exercise", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-golems", name: "Manual of Golems", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-golems-iron", name: "Manual of Iron Golems", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-quickness-of-action", name: "Manual of Quickness of Action", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "manual-of-golems-stone", name: "Manual of Stone Golems", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "figurine-of-wondrous-power-marble-elephant", name: "Marble Elephant Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "marvelous-pigments", name: "Marvelous Pigments", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "medallion-of-thoughts", name: "Medallion of Thoughts", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "mirror-of-life-trapping", name: "Mirror of Life Trapping", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "mithral-armor", name: "Mithral Armor", category: "Armor", rarity: "Uncommon" },
  { id: "necklace-of-adaptation", name: "Necklace of Adaptation", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "necklace-of-fireballs", name: "Necklace of Fireballs", category: "Wondrous Items", rarity: "Rare" },
  { id: "necklace-of-prayer-beads", name: "Necklace of Prayer Beads", category: "Wondrous Items", rarity: "Rare" },
  { id: "nine-lives-stealer", name: "Nine Lives Stealer", category: "Weapon", rarity: "Very Rare" },
  { id: "oathbow", name: "Oathbow", category: "Weapon", rarity: "Very Rare" },
  { id: "figurine-of-wondrous-power-obsidian-steed", name: "Obsidian Steed Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "oil-of-etherealness", name: "Oil of Etherealness", category: "Potion", rarity: "Rare" },
  { id: "oil-of-sharpness", name: "Oil of Sharpness", category: "Potion", rarity: "Very Rare" },
  { id: "oil-of-slipperiness", name: "Oil of Slipperiness", category: "Potion", rarity: "Uncommon" },
  { id: "figurine-of-wondrous-power-onyx-dog", name: "Onyx Dog Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "orb-of-dragonkind", name: "Orb of Dragonkind", category: "Wondrous Items", rarity: "Artifact" },
  { id: "pearl-of-power", name: "Pearl of Power", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "periapt-of-health", name: "Periapt of Health", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "periapt-of-proof-against-poison", name: "Periapt of Proof against Poison", category: "Wondrous Items", rarity: "Rare" },
  { id: "periapt-of-wound-closure", name: "Periapt of Wound Closure", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "philter-of-love", name: "Philter of Love", category: "Potion", rarity: "Uncommon" },
  { id: "pipes-of-haunting", name: "Pipes of Haunting", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "pipes-of-the-sewers", name: "Pipes of the Sewers", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "plate-armor-of-etherealness", name: "Plate Armor of Etherealness", category: "Armor", rarity: "Legendary" },
  { id: "portable-hole", name: "Portable Hole", category: "Wondrous Items", rarity: "Rare" },
  { id: "potion-of-resistance-acid", name: "Potion of Acid Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-animal-friendship", name: "Potion of Animal Friendship", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-clairvoyance", name: "Potion of Clairvoyance", category: "Potion", rarity: "Rare" },
  { id: "potion-of-climbing", name: "Potion of Climbing", category: "Potion", rarity: "Common" },
  { id: "potion-of-giant-strength-cloud", name: "Potion of Cloud Giant Strength", category: "Potion", rarity: "Very Rare" },
  { id: "potion-of-resistance-cold", name: "Potion of Cold Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-diminution", name: "Potion of Diminution", category: "Potion", rarity: "Rare" },
  { id: "potion-of-giant-strength-fire", name: "Potion of Fire Giant Strength", category: "Potion", rarity: "Rare" },
  { id: "potion-of-resistance-fire", name: "Potion of Fire Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-flying", name: "Potion of Flying", category: "Potion", rarity: "Very Rare" },
  { id: "potion-of-resistance-force", name: "Potion of Force Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-giant-strength-frost", name: "Potion of Frost Giant Strength", category: "Potion", rarity: "Rare" },
  { id: "potion-of-gaseous-form", name: "Potion of Gaseous Form", category: "Potion", rarity: "Rare" },
  { id: "potion-of-giant-strength", name: "Potion of Giant Strength", category: "Potion", rarity: "Varies" },
  { id: "potion-of-healing-greater", name: "Potion of Greater Healing", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-growth", name: "Potion of Growth", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-healing", name: "Potion of Healing", category: "Potion", rarity: "Varies" },
  { id: "potion-of-healing-common", name: "Potion of Healing", category: "Potion", rarity: "Common" },
  { id: "potion-of-heroism", name: "Potion of Heroism", category: "Potion", rarity: "Rare" },
  { id: "potion-of-giant-strength-hill", name: "Potion of Hill Giant Strength", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-invisibility", name: "Potion of Invisibility", category: "Potion", rarity: "Very Rare" },
  { id: "potion-of-resistance-lightning", name: "Potion of Lightning Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-mind-reading", name: "Potion of Mind Reading", category: "Potion", rarity: "Rare" },
  { id: "potion-of-resistance-necrotic", name: "Potion of Necrotic Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-poison", name: "Potion of Poison", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-resistance-poison", name: "Potion of Poison Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-resistance-psychic", name: "Potion of Psychic Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-resistance-radiant", name: "Potion of Radiant Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-resistance", name: "Potion of Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-speed", name: "Potion of Speed", category: "Potion", rarity: "Very Rare" },
  { id: "potion-of-giant-strength-stone", name: "Potion of Stone Giant Strength", category: "Potion", rarity: "Rare" },
  { id: "potion-of-giant-strength-storm", name: "Potion of Storm Giant Strength", category: "Potion", rarity: "Legendary" },
  { id: "potion-of-healing-superior", name: "Potion of Superior Healing", category: "Potion", rarity: "Rare" },
  { id: "potion-of-healing-supreme", name: "Potion of Supreme Healing", category: "Potion", rarity: "Very Rare" },
  { id: "potion-of-resistance-thunder", name: "Potion of Thunder Resistance", category: "Potion", rarity: "Uncommon" },
  { id: "potion-of-water-breathing", name: "Potion of Water Breathing", category: "Potion", rarity: "Uncommon" },
  { id: "dragon-scale-mail-red", name: "Red Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "restorative-ointment", name: "Restorative Ointment", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "ring-of-resistance-acid", name: "Ring of Acid Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-elemental-command-air", name: "Ring of Air Elemental Command", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-animal-influence", name: "Ring of Animal Influence", category: "Ring", rarity: "Rare" },
  { id: "ring-of-resistance-cold", name: "Ring of Cold Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-djinni-summoning", name: "Ring of Djinni Summoning", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-elemental-command-earth", name: "Ring of Earth Elemental Command", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-elemental-command", name: "Ring of Elemental Command", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-evasion", name: "Ring of Evasion", category: "Ring", rarity: "Rare" },
  { id: "ring-of-feather-falling", name: "Ring of Feather Falling", category: "Ring", rarity: "Rare" },
  { id: "ring-of-elemental-command-fire", name: "Ring of Fire Elemental Command", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-resistance-fire", name: "Ring of Fire Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-resistance-force", name: "Ring of Force Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-free-action", name: "Ring of Free Action", category: "Ring", rarity: "Rare" },
  { id: "ring-of-invisibility", name: "Ring of Invisibility", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-jumping", name: "Ring of Jumping", category: "Ring", rarity: "Uncommon" },
  { id: "ring-of-resistance-lightning", name: "Ring of Lightning Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-mind-shielding", name: "Ring of Mind Shielding", category: "Ring", rarity: "Uncommon" },
  { id: "ring-of-resistance-necrotic", name: "Ring of Necrotic Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-resistance-poison", name: "Ring of Poison Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-protection", name: "Ring of Protection", category: "Ring", rarity: "Rare" },
  { id: "ring-of-resistance-psychic", name: "Ring of Psychic Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-resistance-radiant", name: "Ring of Radiant Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-regeneration", name: "Ring of Regeneration", category: "Ring", rarity: "Very Rare" },
  { id: "ring-of-resistance", name: "Ring of Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-shooting-stars", name: "Ring of Shooting Stars", category: "Ring", rarity: "Very Rare" },
  { id: "ring-of-spell-storing", name: "Ring of Spell Storing", category: "Ring", rarity: "Rare" },
  { id: "ring-of-spell-turning", name: "Ring of Spell Turning", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-swimming", name: "Ring of Swimming", category: "Ring", rarity: "Uncommon" },
  { id: "ring-of-telekinesis", name: "Ring of Telekinesis", category: "Ring", rarity: "Very Rare" },
  { id: "ring-of-three-wishes", name: "Ring of Three Wishes", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-resistance-thunder", name: "Ring of Thunder Resistance", category: "Ring", rarity: "Rare" },
  { id: "ring-of-warmth", name: "Ring of Warmth", category: "Ring", rarity: "Uncommon" },
  { id: "ring-of-elemental-command-water", name: "Ring of Water Elemental Command", category: "Ring", rarity: "Legendary" },
  { id: "ring-of-water-walking", name: "Ring of Water Walking", category: "Ring", rarity: "Uncommon" },
  { id: "ring-of-x-ray-vision", name: "Ring of X-ray Vision", category: "Ring", rarity: "Rare" },
  { id: "ring-of-the-ram", name: "Ring of the Ram", category: "Ring", rarity: "Rare" },
  { id: "robe-of-eyes", name: "Robe of Eyes", category: "Wondrous Items", rarity: "Rare" },
  { id: "robe-of-scintillating-colors", name: "Robe of Scintillating Colors", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "robe-of-stars", name: "Robe of Stars", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "robe-of-useful-items", name: "Robe of Useful Items", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "robe-of-the-archmagi", name: "Robe of the Archmagi", category: "Wondrous Items", rarity: "Legendary" },
  { id: "rod-of-absorption", name: "Rod of Absorption", category: "Rod", rarity: "Very Rare" },
  { id: "rod-of-alertness", name: "Rod of Alertness", category: "Rod", rarity: "Very Rare" },
  { id: "rod-of-lordly-might", name: "Rod of Lordly Might", category: "Rod", rarity: "Legendary" },
  { id: "rod-of-rulership", name: "Rod of Rulership", category: "Rod", rarity: "Rare" },
  { id: "rod-of-security", name: "Rod of Security", category: "Rod", rarity: "Very Rare" },
  { id: "rope-of-climbing", name: "Rope of Climbing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "rope-of-entanglement", name: "Rope of Entanglement", category: "Wondrous Items", rarity: "Rare" },
  { id: "bag-of-tricks-rust", name: "Rust Bag of Tricks", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "scarab-of-protection", name: "Scarab of Protection", category: "Wondrous Items", rarity: "Legendary" },
  { id: "scimitar-of-speed", name: "Scimitar of Speed", category: "Weapon", rarity: "Very Rare" },
  { id: "figurine-of-wondrous-power-serpentine-owl", name: "Serpentine Owl Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Rare" },
  { id: "shield-of-missile-attraction", name: "Shield of Missile Attraction", category: "Armor", rarity: "Rare" },
  { id: "dragon-scale-mail-silver", name: "Silver Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "horn-of-valhalla-silver", name: "Silver Horn of Valhalla", category: "Wondrous Items", rarity: "Rare" },
  { id: "figurine-of-wondrous-power-silver-raven", name: "Silver Raven Figurine of Wondrous Power", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "slippers-of-spider-climbing", name: "Slippers of Spider Climbing", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "sovereign-glue", name: "Sovereign Glue", category: "Wondrous Items", rarity: "Legendary" },
  { id: "spell-scroll", name: "Spell Scroll", category: "Scroll", rarity: "Varies" },
  { id: "spell-scroll-1st", name: "Spell Scroll (1st)", category: "Scroll", rarity: "Common" },
  { id: "spell-scroll-2nd", name: "Spell Scroll (2nd)", category: "Scroll", rarity: "Uncommon" },
  { id: "spell-scroll-3rd", name: "Spell Scroll (3rd)", category: "Scroll", rarity: "Uncommon" },
  { id: "spell-scroll-4th", name: "Spell Scroll (4th)", category: "Scroll", rarity: "Rare" },
  { id: "spell-scroll-5th", name: "Spell Scroll (5th)", category: "Scroll", rarity: "Rare" },
  { id: "spell-scroll-6th", name: "Spell Scroll (6th)", category: "Scroll", rarity: "Very Rare" },
  { id: "spell-scroll-7th", name: "Spell Scroll (7th)", category: "Scroll", rarity: "Very Rare" },
  { id: "spell-scroll-8th", name: "Spell Scroll (8th)", category: "Scroll", rarity: "Very Rare" },
  { id: "spell-scroll-9th", name: "Spell Scroll (9th)", category: "Scroll", rarity: "Legendary" },
  { id: "spell-scroll-cantrip", name: "Spell Scroll (Cantrip)", category: "Scroll", rarity: "Common" },
  { id: "spellguard-shield", name: "Spellguard Shield", category: "Armor", rarity: "Very Rare" },
  { id: "sphere-of-annihilation", name: "Sphere of Annihilation", category: "Wondrous Items", rarity: "Legendary" },
  { id: "staff-of-charming", name: "Staff of Charming", category: "Staff", rarity: "Rare" },
  { id: "staff-of-fire", name: "Staff of Fire", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-frost", name: "Staff of Frost", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-healing", name: "Staff of Healing", category: "Staff", rarity: "Rare" },
  { id: "staff-of-power", name: "Staff of Power", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-striking", name: "Staff of Striking", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-swarming-insects", name: "Staff of Swarming Insects", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-thunder-and-lightning", name: "Staff of Thunder and Lightning", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-withering", name: "Staff of Withering", category: "Staff", rarity: "Rare" },
  { id: "staff-of-the-magi", name: "Staff of the Magi", category: "Staff", rarity: "Legendary" },
  { id: "staff-of-the-python", name: "Staff of the Python", category: "Staff", rarity: "Very Rare" },
  { id: "staff-of-the-woodlands", name: "Staff of the Woodlands", category: "Staff", rarity: "Rare" },
  { id: "stone-of-controlling-earth-elementals", name: "Stone of Controlling Earth Elementals", category: "Wondrous Items", rarity: "Rare" },
  { id: "stone-of-good-luck-luckstone", name: "Stone of Good Luck (Luckstone)", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "sun-blade", name: "Sun Blade", category: "Weapon", rarity: "Rare" },
  { id: "feather-token-swan-boat", name: "Swan Boat Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "sword-of-life-stealing", name: "Sword of Life Stealing", category: "Weapon", rarity: "Rare" },
  { id: "sword-of-sharpness", name: "Sword of Sharpness", category: "Weapon", rarity: "Very Rare" },
  { id: "sword-of-wounding", name: "Sword of Wounding", category: "Weapon", rarity: "Rare" },
  { id: "talisman-of-pure-good", name: "Talisman of Pure Good", category: "Wondrous Items", rarity: "Legendary" },
  { id: "talisman-of-ultimate-evil", name: "Talisman of Ultimate Evil", category: "Wondrous Items", rarity: "Legendary" },
  { id: "talisman-of-the-sphere", name: "Talisman of the Sphere", category: "Wondrous Items", rarity: "Legendary" },
  { id: "bag-of-tricks-tan", name: "Tan Bag of Tricks", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "tome-of-clear-thought", name: "Tome of Clear Thought", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "tome-of-leadership-and-influence", name: "Tome of Leadership and Influence", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "tome-of-understanding", name: "Tome of Understanding", category: "Wondrous Items", rarity: "Very Rare" },
  { id: "feather-token-tree", name: "Tree Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "trident-of-fish-command", name: "Trident of Fish Command", category: "Weapon", rarity: "Uncommon" },
  { id: "universal-solvent", name: "Universal Solvent", category: "Wondrous Items", rarity: "Legendary" },
  { id: "vicious-weapon", name: "Vicious Weapon", category: "Weapon", rarity: "Rare" },
  { id: "vorpal-sword", name: "Vorpal Sword", category: "Weapon", rarity: "Legendary" },
  { id: "wand-of-binding", name: "Wand of Binding", category: "Wand", rarity: "Rare" },
  { id: "wand-of-enemy-detection", name: "Wand of Enemy Detection", category: "Wand", rarity: "Rare" },
  { id: "wand-of-fear", name: "Wand of Fear", category: "Wand", rarity: "Rare" },
  { id: "wand-of-fireballs", name: "Wand of Fireballs", category: "Wand", rarity: "Rare" },
  { id: "wand-of-lightning-bolts", name: "Wand of Lightning Bolts", category: "Wand", rarity: "Rare" },
  { id: "wand-of-magic-detection", name: "Wand of Magic Detection", category: "Wand", rarity: "Uncommon" },
  { id: "wand-of-magic-missiles", name: "Wand of Magic Missiles", category: "Wand", rarity: "Uncommon" },
  { id: "wand-of-paralysis", name: "Wand of Paralysis", category: "Wand", rarity: "Rare" },
  { id: "wand-of-polymorph", name: "Wand of Polymorph", category: "Wand", rarity: "Very Rare" },
  { id: "wand-of-secrets", name: "Wand of Secrets", category: "Wand", rarity: "Uncommon" },
  { id: "wand-of-web", name: "Wand of Web", category: "Wand", rarity: "Uncommon" },
  { id: "wand-of-wonder", name: "Wand of Wonder", category: "Wand", rarity: "Rare" },
  { id: "wand-of-the-war-mage-1", name: "Wand of the War Mage, +1", category: "Wand", rarity: "Uncommon" },
  { id: "wand-of-the-war-mage", name: "Wand of the War Mage, +1, +2, or +3", category: "Wand", rarity: "Varies" },
  { id: "wand-of-the-war-mage-2", name: "Wand of the War Mage, +2", category: "Wand", rarity: "Rare" },
  { id: "wand-of-the-war-mage-3", name: "Wand of the War Mage, +3", category: "Wand", rarity: "Very Rare" },
  { id: "elemental-gem-water", name: "Water Elemental Gem", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "weapon-1", name: "Weapon, +1", category: "Weapon", rarity: "Uncommon" },
  { id: "weapon", name: "Weapon, +1, +2, or +3", category: "Weapon", rarity: "Varies" },
  { id: "weapon-2", name: "Weapon, +2", category: "Weapon", rarity: "Rare" },
  { id: "weapon-3", name: "Weapon, +3", category: "Weapon", rarity: "Very Rare" },
  { id: "well-of-many-worlds", name: "Well of Many Worlds", category: "Wondrous Items", rarity: "Legendary" },
  { id: "feather-token-whip", name: "Whip Feather Token", category: "Wondrous Items", rarity: "Rare" },
  { id: "dragon-scale-mail-white", name: "White Dragon Scale Mail", category: "Armor", rarity: "Very Rare" },
  { id: "wind-fan", name: "Wind Fan", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "winged-boots", name: "Winged Boots", category: "Wondrous Items", rarity: "Uncommon" },
  { id: "wings-of-flying", name: "Wings of Flying", category: "Wondrous Items", rarity: "Rare" },
];
